# 应用服务 WEB 访问端口
server.port:
  9090
spring:
  application:
    name: huiyancompare
  datasource:
    url: jdbc:mysql://192.168.2.241:3306/compare-speech-recognition?autoreconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: mysql123
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 60000
      validation-timeout: 5000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 600000


huiyan:
  asr:
    create: http://192.168.2.200:7100/request
    result: http://192.168.2.200:7100/getResult
    delete: http://192.168.2.200:7100/deleteTask

translation:
  transform:
    path: /data/waitrans/asr/
  subtitle:
    path: /data/waitrans/subtitle/